# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    # Group all devcontainer updates into single PR
    groups:
      devcontainer-updates:
        patterns:
          - "*"
    # Only allow minor and patch updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Add cooldown to avoid immature packages
    cooldown:
      default-days: 7
    target-branch: "main"
    labels:
      - "dependencies"
      - "devcontainer"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday" 
      time: "09:00"
      timezone: "UTC"
    # Group npm updates by type to reduce PR count
    groups:
      npm-production:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "*-dev"
          - "eslint*"
          - "webpack*"
          - "babel*"
        update-types:
          - "minor"
          - "patch"
      npm-development:
        patterns:
          - "@types/*"
          - "*-dev" 
          - "eslint*"
          - "webpack*"
          - "babel*"
        update-types:
          - "minor"
          - "patch"
    # Only allow minor and patch updates, no major versions
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Limit number of open PRs
    open-pull-requests-limit: 3
    # Add cooldown to avoid immature packages
    cooldown:
      default-days: 7
    target-branch: "main"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00" 
      timezone: "UTC"
    # Group all GitHub Actions updates into single PR
    groups:
      github-actions:
        patterns:
          - "*"
    # Only allow minor and patch updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Add cooldown to avoid immature packages
    cooldown:
      default-days: 7
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
